{% set version = "4.0.3" %}

package:
  name: pypubsub
  version: {{ version }}

source:
  url: https://github.com/schollii/pypubsub/archive/v{{ version }}.tar.gz
  sha256: 0ae266d3bcf8e6c5852eeca4ce30114863bc9f6eaae27bda99de737c9f8d1538
  
build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  imports:
    - pubsub

about:
  license: BSD-2-Clause
  license_file: src/pubsub/LICENSE_BSD_Simple.txt
  license_family: BSD
  summary: A python publish-subscribe library
  home: https://github.com/schollii/pypubsub

extra:
  recipe-maintainers:
    - constantinpape
    - schollii
