travis:
  secure:
    BINSTAR_TOKEN: iicYgMsYwFPcxNu3WPZZhQOG1hvv/6xpSqeV10oLK/8x1ab7ncGWyrFoaClzgMvlFPJYCdJG1wO9LDot/k4E1pce/ouWUdenoIq+VYMzGWztP3UXJXFGvi8zIM0PdNBC9uxyGZBpWwE0uG0a8BjxpUAYxD7DMe/eOIMhUITvl2SVDHQbF9axfhbmkSY69JDCRaZm30uWrZWlZj3WUqlOEUoVFgxnoaWdm9RrxQc5gB9U8wqQy9P/L2Jr6eS5CXByrF+Ec3vZRBSYJkE5vQowgMqD3XF9z0KPB3A6LaJxkBYggJuVws45PiN42YvXYvY4IK2zAD61tSD+VDD1Q4468dF5cDfDsh3ycsw0jeLPqaaj64yu+bKnIgsf1p7/wSFUevT04inY4d4rEoo4XxF0WyMYUIiJvargkF/haHuOOJ5+D+fZoRsl4eblb766ZHVV27feDCTnNAocUYds44wEqh4QDn6GhRtTbv7u//e6mv/fp1H+0ow2FIrsVmBoCilDq3xx5cDogfsAsWtIzRjpfkE16kEjCZ/J8gFJy6i1KJjyyKRc6NOci3j/1Bg1j+/2VCsxT9gSOagEXbKEKNeQtQ/DvsYsVOOZsWv4qqOy7zmC1hcKGSnTgdu4XUtVNK39JNb4gCoIYl3zNUhQrkk0/vlycpR2aT4MMHwOcj0MACQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
